name: Merge to Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  merge-to-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Merge Feature Branch to Master
        run: |
          git fetch origin +refs/heads/${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          git merge --no-ff origin/${{ github.event.pull_request.head.ref }}
          git push origin master
