name: Regular Master Merge Workflow

on:
  push:
    branches:
      - master

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Configure Git (Identify Author)
        run: |
          git config user.name "Zain"
          git config user.email "zainazharul@gmail.com"

      - name: Update UAT
        run: |
          git fetch origin uat 
          git checkout uat
          git merge master
          git push https://x-access-token:${{ secrets.PAT }}@github.com/zenzett/flixflop.git uat

      - name: Update Staging
        run: |
          git fetch origin staging 
          git checkout staging 
          git merge master
          git push https://x-access-token:${{ secrets.PAT }}@github.com/zenzett/flixflop.git staging
